import LinkedRenderStore, { RENDER_CLASS_NAME } from 'link-lib';

import { NS } from '../../helpers/LinkedRenderStore';
import {
  Loading,
  LoadingSideBarLink,
  LoadingCard,
  LoadingCardFixed,
  LoadingMicroRow,
  LoadingDetail,
  LoadingPage,
  LoadingParent,
  LoadingRow,
} from '../../components';

export default [
  LinkedRenderStore.registerRenderer(
    LoadingPage,
    NS.ll('LoadingResource')
  ),
  LinkedRenderStore.registerRenderer(
    LoadingParent,
    NS.ll('LoadingResource'),
    RENDER_CLASS_NAME,
    NS.argu('parent')
  ),
  LinkedRenderStore.registerRenderer(
    LoadingCard,
    NS.ll('LoadingResource'),
    RENDER_CLASS_NAME,
    [
      NS.argu('container'),
      NS.argu('cardList'),
    ]
  ),
  LinkedRenderStore.registerRenderer(
    LoadingCardFixed,
    NS.ll('LoadingResource'),
    RENDER_CLASS_NAME,
    [
      NS.argu('grid'),
      NS.argu('widget'),
    ]
  ),
  LinkedRenderStore.registerRenderer(
    LoadingMicroRow,
    NS.ll('LoadingResource'),
    RENDER_CLASS_NAME,
    [
      NS.argu('cardRow'),
    ]
  ),
  LinkedRenderStore.registerRenderer(
    LoadingRow,
    NS.ll('LoadingResource'),
    RENDER_CLASS_NAME,
    [
      NS.argu('card'),
      NS.argu('cardFixed'),
      NS.argu('cardHover'),
      NS.argu('cardMain'),
    ]
  ),
  LinkedRenderStore.registerRenderer(
    LoadingSideBarLink,
    NS.ll('LoadingResource'),
    RENDER_CLASS_NAME,
    [
      NS.argu('dropdownContent'),
      NS.argu('sidebar'),
    ]
  ),
  LinkedRenderStore.registerRenderer(
    LoadingDetail,
    NS.ll('LoadingResource'),
    RENDER_CLASS_NAME,
    NS.argu('detail')
  ),
  LinkedRenderStore.registerRenderer(
    Loading,
    NS.ll('LoadingResource'),
    RENDER_CLASS_NAME,
    [
      NS.argu('cardList'),
      NS.argu('inline'),
      NS.argu('voteBubble'),
      NS.argu('cardMain'),
    ]
  ),
];
