// TextEditor
export const TEXT_EDITOR_UPDATE_DRAFT = 'TEXT_EDITOR_UPDATE_DRAFT';
export const TEXT_EDITOR_UPDATE_MARKDOWN = 'TEXT_EDITOR_UPDATE_MARKDOWN';
export const TEXT_EDITOR_SWITCH_TO_MARKDOWN = 'TEXT_EDITOR_SWITCH_TO_MARKDOWN';
export const TEXT_EDITOR_SWITCH_TO_DRAFT = 'TEXT_EDITOR_SWITCH_TO_DRAFT';
export const MARKDOWN_EDITOR_SHOW_PREVIEW = 'MARKDOWN_EDITOR_SHOW_PREVIEW';
export const MARKDOWN_EDITOR_HIDE_PREVIEW = 'MARKDOWN_EDITOR_HIDE_PREVIEW';
