// API
export const AFE_API_LOGIN = '@AFE_API/LOGIN';
export const AFE_API_GET_MAP_ACCESS_TOKEN = '@AFE_API/GET_MAP_ACCESS_TOKEN';

// App
export const HIGHLIGHT_RESOURCE = 'HIGHLIGHT_RESOURCE';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';

// Collapsibles
export const COLL_ADD = 'COLL_ADD';
export const COLL_REMOVE = 'COLL_REMOVE';
export const COLL_CLOSE_ONE = 'COLL_CLOSE_ONE';
export const COLL_OPEN_GROUPED = 'COLL_OPEN_GROUPED';
export const COLL_TOGGLE_ONE = 'COLL_TOGGLE_ONE';
export const COLL_TOGGLE_GROUP = 'COLL_TOGGLE_GROUP';

// Closeable
export const CLOSEABLE_ADD = 'CLOSEABLE_ADD';
export const CLOSEABLE_CLOSE = 'CLOSEABLE_CLOSE';

// Form
export const SIGN_IN_ACCOUNT_LOCKED = 'SIGN_IN_ACCOUNT_LOCKED';
export const SIGN_IN_EMAIL_TAKEN = 'SIGN_IN_EMAIL_TAKEN';
export const SIGN_IN_LOGGED_IN = 'SIGN_IN_LOGGED_IN';
export const SIGN_IN_SHOW_FORM = 'SIGN_IN_SHOW_FORM';
export const SIGN_IN_STEP_BACK = 'SIGN_IN_STEP_BACK';
export const SIGN_IN_UNKNOWN_EMAIL = 'SIGN_IN_UNKNOWN_EMAIL';
export const SIGN_IN_UNKNOWN_USERNAME = 'SIGN_IN_UNKNOWN_USERNAME';
export const SIGN_IN_USER_CREATED = 'SIGN_IN_USER_CREATED';
export const SIGN_IN_WRONG_PASSWORD = 'SIGN_IN_WRONG_PASSWORD';

// Map view
export const MAP_SET_ACCESS_TOKEN = 'MAP_SET_ACCESS_TOKEN';

// TextEditor
export const TEXT_EDITOR_UPDATE_DRAFT = 'TEXT_EDITOR_UPDATE_DRAFT';
export const TEXT_EDITOR_UPDATE_MARKDOWN = 'TEXT_EDITOR_UPDATE_MARKDOWN';
export const TEXT_EDITOR_SWITCH_TO_MARKDOWN = 'TEXT_EDITOR_SWITCH_TO_MARKDOWN';
export const TEXT_EDITOR_SWITCH_TO_DRAFT = 'TEXT_EDITOR_SWITCH_TO_DRAFT';
export const MARKDOWN_EDITOR_SHOW_PREVIEW = 'MARKDOWN_EDITOR_SHOW_PREVIEW';
export const MARKDOWN_EDITOR_HIDE_PREVIEW = 'MARKDOWN_EDITOR_HIDE_PREVIEW';

// Motions & voting
export const GET_MOTIONS = 'GET_MOTIONS';
export const GET_MOTION = 'GET_MOTION';

export const GET_COUNTS = 'GET_COUNTS';
export const GET_COUNT = 'GET_COUNT';

export const GET_VOTES = 'GET_VOTES';
export const GET_VOTE = 'GET_VOTE';

export const GET_VOTE_EVENTS = 'GET_VOTE_EVENTS';
export const GET_VOTE_EVENT = 'GET_VOTE_EVENT';

// Pagination
export const GOTO_PAGE = 'GOTO_PAGE';

// PDFViewer
export const PDF_SET_NUM_PAGES = 'PDF_SET_NUM_PAGES';
export const PDF_SET_ROTATION = 'PDF_SET_ROTATION';
export const PDF_SET_ZOOM_LEVEL = 'PDF_SET_ZOOM_LEVEL';
export const PDF_SET_SHOW_COMMENTS = 'PDF_SET_SHOW_COMMENTS';

// react-router
export const LOCATION_CHANGE = 'LOCATION_CHANGE';

// Omniform
export const OMNIFORM_ADD_ACTION = 'OMNIFORM_ADD_ACTION';
export const OMNIFORM_CLOSE_INLINE = 'OMNIFORM_CLOSE_INLINE';
export const OMNIFORM_INITIALIZE = 'OMNIFORM_INITIALIZE';
export const OMNIFORM_OPEN_INLINE = 'OMNIFORM_OPEN_INLINE';
export const OMNIFORM_SET_ACTION = 'OMNIFORM_SET_ACTION';

// Popups
export const SET_POPUP_RESOURCE = 'SET_POPUP_RESOURCE';
export const UNSET_POPUP_RESOURCE = 'UNSET_POPUP_RESOURCE';

// VoteMatch
export const VOTE_MATCH_ADD_VOTEABLE = 'VOTE_MATCH_ADD_VOTEABLE';
export const VOTE_MATCH_INIT = 'VOTE_MATCH_INIT';
export const VOTE_MATCH_NEXT = 'VOTE_MATCH_NEXT';
export const VOTE_MATCH_REMOVE_VOTEABLE = 'VOTE_MATCH_REMOVE_VOTEABLE';
export const VOTE_MATCH_SAVE = 'VOTE_MATCHES_SAVE';
export const VOTE_MATCH_TRANSITION_TO = 'VOTE_MATCH_TRANSITION_TO';
export const VOTE_MATCH_UPDATE_VOTEABLES = 'VOTE_MATCHES_UPDATE_MOTIONS';

export const GET_VOTE_MATCH = 'GET_VOTE_MATCH';
export const GET_VOTE_MATCHES = 'GET_VOTE_MATCHES';
export const CREATE_VOTE_MATCH = 'CREATE_VOTE_MATCH';
