// App
export const HIGHLIGHT_RESOURCE = 'HIGHLIGHT_RESOURCE';
export const SET_ORGANIZATION = 'SET_ORGANIZATION';

// Collapsibles
export const COLL_ADD = 'COLL_ADD';
export const COLL_REMOVE = 'COLL_REMOVE';
export const COLL_CLOSE_ONE = 'COLL_CLOSE_ONE';
export const COLL_OPEN_GROUPED = 'COLL_OPEN_GROUPED';
export const COLL_TOGGLE_ONE = 'COLL_TOGGLE_ONE';
export const COLL_TOGGLE_GROUP = 'COLL_TOGGLE_GROUP';

// Form
export const EMAIL_TAKEN = 'EMAIL_TAKEN';

// Iframe
export const IFRAME_METADATA = 'IFRAME_METADATA';

// TextEditor
export const TEXT_EDITOR_UPDATE_DRAFT = 'TEXT_EDITOR_UPDATE_DRAFT';
export const TEXT_EDITOR_UPDATE_MARKDOWN = 'TEXT_EDITOR_UPDATE_MARKDOWN';
export const TEXT_EDITOR_SWITCH_TO_MARKDOWN = 'TEXT_EDITOR_SWITCH_TO_MARKDOWN';
export const TEXT_EDITOR_SWITCH_TO_DRAFT = 'TEXT_EDITOR_SWITCH_TO_DRAFT';
export const MARKDOWN_EDITOR_SHOW_PREVIEW = 'MARKDOWN_EDITOR_SHOW_PREVIEW';
export const MARKDOWN_EDITOR_HIDE_PREVIEW = 'MARKDOWN_EDITOR_HIDE_PREVIEW';

// Motions & voting
export const GET_MOTIONS = 'GET_MOTIONS';
export const GET_MOTION = 'GET_MOTION';

export const GET_COUNTS = 'GET_COUNTS';
export const GET_COUNT = 'GET_COUNT';

export const GET_VOTES = 'GET_VOTES';
export const GET_VOTE = 'GET_VOTE';

export const GET_VOTE_EVENTS = 'GET_VOTE_EVENTS';
export const GET_VOTE_EVENT = 'GET_VOTE_EVENT';

// Pagination
export const GOTO_PAGE = 'GOTO_PAGE';

// Omniform
export const OMNIFORM_ADD_ACTION = 'OMNIFORM_ADD_ACTION';
export const OMNIFORM_INITIALIZE = 'OMNIFORM_INITIALIZE';
export const OMNIFORM_SET_TYPE = 'OMNIFORM_SET_TYPE';

// Popups
export const SET_POPUP_RESOURCE = 'SET_POPUP_RESOURCE';
export const UNSET_POPUP_RESOURCE = 'UNSET_POPUP_RESOURCE';

// Search
export const TOGGLE_DRAWER = 'TOGGLE_DRAWER';
export const SET_HIT_COUNT = 'SET_HIT_COUNT';

export const RESET_ERROR_MESSAGE = 'RESET_ERROR_MESSAGE';

// SideBar
export const SIDEBAR_ADD = 'SIDEBAR_ADD';
export const SIDEBAR_OPEN = 'SIDEBAR_OPEN';
export const SIDEBAR_CLOSE = 'SIDEBAR_CLOSE';
export const SIDEBAR_DOCK = 'SIDEBAR_DOCK';
export const SIDEBAR_SET_BASE_COLOR = 'SIDEBAR_SET_BASE_COLOR';
export const SIDEBAR_UNDOCK = 'SIDEBAR_UNDOCK';

// VoteMatch
export const VOTE_MATCH_ADD_VOTEABLE = 'VOTE_MATCH_ADD_VOTEABLE';
export const VOTE_MATCH_INIT = 'VOTE_MATCH_INIT';
export const VOTE_MATCH_NEXT = 'VOTE_MATCH_NEXT';
export const VOTE_MATCH_REMOVE_VOTEABLE = 'VOTE_MATCH_REMOVE_VOTEABLE';
export const VOTE_MATCH_SAVE = 'VOTE_MATCHES_SAVE';
export const VOTE_MATCH_TRANSITION_TO = 'VOTE_MATCH_TRANSITION_TO';
export const VOTE_MATCH_UPDATE_VOTEABLES = 'VOTE_MATCHES_UPDATE_MOTIONS';

export const GET_VOTE_MATCH = 'GET_VOTE_MATCH';
export const GET_VOTE_MATCHES = 'GET_VOTE_MATCHES';
export const CREATE_VOTE_MATCH = 'CREATE_VOTE_MATCH';
