// App
export const HIGHLIGHT_RESOURCE = 'HIGHLIGHT_RESOURCE';

// TextEditor
export const TEXT_EDITOR_UPDATE_DRAFT = 'TEXT_EDITOR_UPDATE_DRAFT';
export const TEXT_EDITOR_UPDATE_MARKDOWN = 'TEXT_EDITOR_UPDATE_MARKDOWN';
export const TEXT_EDITOR_SWITCH_TO_MARKDOWN = 'TEXT_EDITOR_SWITCH_TO_MARKDOWN';
export const TEXT_EDITOR_SWITCH_TO_DRAFT = 'TEXT_EDITOR_SWITCH_TO_DRAFT';
export const MARKDOWN_EDITOR_SHOW_PREVIEW = 'MARKDOWN_EDITOR_SHOW_PREVIEW';
export const MARKDOWN_EDITOR_HIDE_PREVIEW = 'MARKDOWN_EDITOR_HIDE_PREVIEW';

// Omniform
export const OMNIFORM_CLOSE_INLINE = 'OMNIFORM_CLOSE_INLINE';
export const OMNIFORM_OPEN_INLINE = 'OMNIFORM_OPEN_INLINE';
export const OMNIFORM_SET_ACTION = 'OMNIFORM_SET_ACTION';
