export { default as app } from './app/reducer';
export { default as collapsible } from './collapsible/reducer';
export { default as communication } from './communication/reducer';
export { default as form } from './form/reducer';
export { default as iframe } from './iframe/reducer';
export { linkReducer as linkedObjects } from 'link-redux';
export { default as pagination } from './pagination/reducer';
export { default as router } from './router/reducer';
// export { default as searchElastic } from './searchElastic/reducer';
export { default as sideBars } from './sideBars/reducer';
// export { default as voteMatch } from './voteMatch/reducer';
