image: node:lts-slim

cache:
  key: $CI_PROJECT_ID
  paths:
    - .yarn/cache
    - tmp/

variables:
  DOCKER_TLS_CERTDIR: "/certs"
  DOCKER_HOST: tcp://docker:2376

default:
  before_script:
    - apt update && apt install -y git
    - yarn --immutable
    - yarn run t10s:compile

stages:
  - build
  - bake

build:
  stage: build
  script:
    - yarn run build:bundle
    - yarn run build:shared
  artifacts:
    paths:
      - dist

codeQuality:
  stage: build
  script:
    - echo "${CI_COMMIT_MESSAGE}" | npx commitlint
    - yarn run lint:code
    - yarn run t10s:lint

test:
  stage: build
  script:
    - ./node_modules/.bin/jest --coverage --coverageReporters="text-summary" --no-cache
  coverage: '/Lines.+\d+.\d+%/'

bake:
  stage: bake
  image: docker:20.10.17
  services:
    - docker:20.10.17-dind
  before_script:
    - echo "$HUB_TOKEN" | docker login -u "$HUB_USER" "docker.io" --password-stdin
  needs:
    - build
  script:
    - apk add git
    - git describe --always > ./client_version.txt
    - docker build --tag argu/libro-client:$CI_COMMIT_SHA .
    - docker push argu/libro-client:$CI_COMMIT_SHA

tag_latest:
  stage: bake
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  needs:
    - bake
  services:
    - 'docker:20.10.12-dind'
  before_script:
    - echo "$HUB_TOKEN" | docker login -u "$HUB_USER" "docker.io" --password-stdin
  script:
    - docker pull argu/libro-client:$CI_COMMIT_SHA
    - docker tag argu/libro-client:$CI_COMMIT_SHA argu/libro-client:latest
    - docker manifest push --purge argu/libro-client:latest

