image: node

before_script:
  - node -v
  - npm -v
  - npm i

stages:
  - lint
  - build
  - test
  - bake
  - deploy

job1:
  stage: lint
  script:
    - npm run lint

job2:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
    - dist/
  only:
    - master

job3:
  stage: test
  script:
    - npm run test

job4:
  stage: bake
  script:
    - docker build --pull=true -t registry.gitlab.com/arguweb/aod_demo .
    - docker push registry.gitlab.com/arguweb/aod_demo
