image: node

cache:
  paths:
  - node_modules/

before_script:
  - node -v
  - npm -v
  - npm i

build:
  stage: build
  script:
    - npm run build
  only:
    - master

test:
  stage: test
  script:
    - npm run lint
    - npm run test
    - npm run e2e

bake:
  stage: bake
  script:
    - docker build --pull=true -t registry.gitlab.com/arguweb/aod_demo .
    - docker push registry.gitlab.com/arguweb/aod_demo
