before_script:
  - docker info
  - node -v
  - npm -v
  - npm i

stages:
  - build
  - test
  - bake
  - release

build:
  stage: build
  script:
    - npm run build
  only:
    - master

test:
  stage: test
  script:
    - npm run lint
    - npm run test

bake:
  stage: bake
  script:
    - docker build --pull=true -t registry.gitlab.com/argu/aod_demo:${CI_BUILD_REF_NAME} .

tag:
  stage: release
  script:
    - docker push registry.gitlab.com/argu/aod_demo:${CI_BUILD_REF_NAME}

latest:
  stage: release
  script:
    - docker tag registry.gitlab.com/argu/aod_demo:${CI_BUILD_REF_NAME} registry.gitlab.com/argu/aod_demo:latest
    - docker push registry.gitlab.com/argu/aod_demo:latest
  only:
    - master
