image: node

before_script:
  - docker info
  - node -v
  - npm -v
  - npm i

stages:
  - build
  - test
  - bake
  - deploy

build:
  stage: build
  script:
    - npm run build
  only:
    - master

test:
  stage: test
  script:
    - npm run lint
    - npm run test

bake:
  stage: bake
  script:
    - docker build --pull=true -t registry.gitlab.com/arguweb/aod_demo .
    - docker push registry.gitlab.com/arguweb/aod_demo
