FROM node:4.4

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

COPY package.json /usr/src/app/
RUN yarn install
COPY . /usr/src/app

ENV NODE_ENV 'production'
ENV ELASTICSEARCH_URL ''
ENV ELASTICSEARCH_INDEX ''
ENV ARGU_API_URL 'http://localhost:3030/'

RUN yarn run build
RUN npm prune -q --prod

EXPOSE 8080
CMD yarn run start:prod
