FROM node:9-alpine

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

COPY package.json /usr/src/app/
RUN npm i -q
COPY . /usr/src/app

ENV NODE_ENV 'production'
ARG ARGU_API_URL
ENV ARGU_API_URL $ARGU_API_URL

RUN npm run build
RUN npm prune -q --prod

EXPOSE 8080
CMD npm run start:prod
