import { createNS } from '@ontologies/core';

const ontola = createNS('https://ns.ontola.io/');

export default {
  ns: ontola,

  /* classes */
  Collection: ontola('Collection'),
  CollectionSorting: ontola('CollectionSorting'),
  CollectionView: ontola('CollectionView'),
  ConfirmedUser: ontola('ConfirmedUser'),
  ['Create::FollowUp']: ontola('Create::FollowUp'),
  ['Create::Opinion']: ontola('Create::Opinion'),
  ['Create::Users::Password']: ontola('Create::Users::Password'),
  ['Create::Users::Confirmation']: ontola('Create::Users::Confirmation'),
  ['Create::Users::Unlock']: ontola('Create::Users::Unlock'),
  ['Create::Vote']: ontola('Create::Vote'),
  CreateVoteAction: ontola('CreateVoteAction'),
  DestroyVoteAction: ontola('DestroyVoteAction'),
  DisabledActionStatus: ontola('DisabledActionStatus'),
  ExpiredActionStatus: ontola('ExpiredActionStatus'),
  FilteredCollection: ontola('FilteredCollection'),
  FormOption: ontola('FormOption'),
  FormStep: ontola('FormStep'),
  GuestUser: ontola('GuestUser'),
  InfiniteView: ontola('InfiniteView'),
  MenuItem: ontola('MenuItem'),
  PaginatedView: ontola('PaginatedView'),
  PropertyQuery: ontola('PropertyQuery'),
  SearchResult: ontola('SearchResult'),
  UnconfirmedUser: ontola('UnconfirmedUser'),
  VideoPage: ontola('VideoPage'),
  Widget: ontola('Widget'),

  /* properties */
  _destroy: ontola('_destroy'),
  action: ontola('action'),
  actionsMenu: ontola('actionsMenu'),
  actor: ontola('actor'),
  actorType: ontola('actorType'),
  baseCollection: ontola('baseCollection'),
  collectionDisplay: ontola('collectionDisplay'),
  ['collectionDisplay/card']: ontola('collectionDisplay/card'),
  ['collectionDisplay/default']: ontola('collectionDisplay/default'),
  ['collectionDisplay/grid']: ontola('collectionDisplay/grid'),
  ['collectionDisplay/settingsTable']: ontola('collectionDisplay/settingsTable'),
  ['collectionDisplay/table']: ontola('collectionDisplay/table'),
  collectionFrame: ontola('collectionFrame'),
  collectionSorting: ontola('collectionSorting'),
  collectionType: ontola('collectionType'),
  ['collectionType/infinite']: ontola('collectionType/infinite'),
  ['collectionType/paginated']: ontola('collectionType/paginated'),
  columns: ontola('columns'),
  coverPhoto: ontola('coverPhoto'),
  createAction: ontola('createAction'),
  createSubmissionAction: ontola('createSubmissionAction'),
  defaultPagination: ontola('defaultPagination'),
  defaultType: ontola('defaultType'),
  destroyAction: ontola('destroyAction'),
  favoriteAction: ontola('favoriteAction'),
  filteredCollections: ontola('filteredCollections'),
  followMenu: ontola('followMenu'),
  footerGroup: ontola('footerGroup'),
  ['forms/inputs/select/displayProp']: ontola('forms/inputs/select/displayProp'),
  formSteps: ontola('formSteps'),
  header: ontola('header'),
  helperText: ontola('helperText'),
  hiddenGroup: ontola('hiddenGroup'),
  href: ontola('href'),
  imagePositionY: ontola('imagePositionY'),
  imgUrl1500x2000: ontola('imgUrl1500x2000'),
  imgUrl256x256: ontola('imgUrl256x256'),
  imgUrl568x400: ontola('imgUrl568x400'),
  imgUrl64x64: ontola('imgUrl64x64'),
  infinitePagination: ontola('infinitePagination'),
  inputFieldHint: ontola('inputFieldHint'),
  invalidate: ontola('invalidate'),
  iriTemplate: ontola('iriTemplate'),
  iriTemplateOpts: ontola('iriTemplateOpts'),
  makePrimaryAction: ontola('makePrimaryAction'),
  memberships: ontola('memberships'),
  menuItems: ontola('menuItems'),
  menus: ontola('menus'),
  navigationsMenu: ontola('navigationsMenu'),
  organization: ontola('organization'),
  pages: ontola('pages'),
  parentMenu: ontola('parentMenu'),
  profileMenu: ontola('profileMenu'),
  publishAction: ontola('publishAction'),
  readAction: ontola('readAction'),
  relevance: ontola('relevance'),
  remove: ontola('remove'),
  replace: ontola('replace'),
  sendConfirmationAction: ontola('sendConfirmationAction'),
  settingsMenu: ontola('settingsMenu'),
  shareMenu: ontola('shareMenu'),
  sortDirection: ontola('sortDirection'),
  sortKey: ontola('sortKey'),
  sortOptions: ontola('sortOptions'),
  topology: ontola('topology'),
  updateAction: ontola('updateAction'),
  widgetResource: ontola('widgetResource'),
  widgetSize: ontola('widgetSize'),
  widgets: ontola('widgets'),
};
