import classNames from 'classnames';
import PropTypes from 'prop-types';
import React from 'react';

import { TextEditor } from '../../components';

import './FormField.scss';

const propTypes = {
  autoComplete: PropTypes.string,
  autoFocus: PropTypes.bool,
  // Preferably use variants to style this component.
  className: PropTypes.string,
  // E.g. 'input' or 'textArea'
  element: PropTypes.string,
  // Unique identifier. Used to link label to input.
  id: PropTypes.string.isRequired,
  // Contains data from redux-form, such as values
  input: PropTypes.shape({
    values: PropTypes.arrayOf(PropTypes.string),
  }),
  // Text above input field
  label: PropTypes.string,
  // Generated by Redux-form. Contains value and error data.
  // http://redux-form.com/6.4.3/docs/api/Field.md/
  meta: PropTypes.shape({
    active: PropTypes.bool,
    dirty: PropTypes.bool,
    error: PropTypes.string,
    touched: PropTypes.bool,
    warning: PropTypes.string,
  }),
  placeholder: PropTypes.string,
  // Enables the rich (markdown) text editor
  rich: PropTypes.bool,
  // Number of rows for textAreas
  rows: PropTypes.number,
  // HTML input type, e.g. 'email'
  type: PropTypes.string,
  // Modify te look and feel of the FormField
  variant: PropTypes.oneOf(['material', 'preview']),
};

const defaultProps = {
  autoComplete: 'false',
  autoFocus: 'false',
  element: 'input',
  meta: {},
  rich: false,
  variant: 'default',
};

const MessagesProps = {
  bottom: propTypes.bool,
  error: propTypes.string,
  warning: propTypes.string,
};

const MessagesDefaultProps = {
  bottom: false,
};

const Messages = ({ error, warning, bottom }) => (
  <div className={`Field__messages ${bottom ? 'Field__messages--bottom' : ''}`}>
    {((error &&
      <span className="Field__error">
        {error}
      </span>
    ) || (warning &&
      <span className="Field__warning">
        {warning}
      </span>
    ))}
  </div>
);

Messages.propTypes = MessagesProps;
Messages.defaultProps = MessagesDefaultProps;

/**
 * Creates a field for forms. Use with redux-form Field if possible.
 * @returns {component} Component
 */
const FormField = ({
  autoComplete,
  autoFocus,
  className,
  rows,
  placeholder,
  input,
  element,
  label,
  rich,
  type,
  id,
  variant,
  meta: {
    active,
    dirty,
    error,
    touched,
    warning,
  },
}) => {
  const Element = rich === true ? TextEditor : element;

  const classes = classNames({
    Field: true,
    [`Field--variant-${variant}`]: variant,
    'Field--active': active,
    'Field--dirty': dirty,
    'Field--error': error,
    'Field--textarea': (type === 'textarea'),
    'Field--warning': warning,
    className,
  });

  const renderMessages = touched && (error || warning);

  const messagesAboveLabel = (variant !== 'material');

  return (
    <div className={`Field ${className} ${classes}`}>
      {renderMessages && messagesAboveLabel &&
        <Messages error={error} warning={warning} />
      }
      {label &&
        <label
          className="Field__label"
          htmlFor={id}
        >
          {label}
        </label>
      }
      <Element
        {...input}
        autoComplete={autoComplete}
        autoFocus={autoFocus}
        className="Field__input"
        id={id}
        placeholder={placeholder}
        rows={rows}
        type={type}
        onBlur={input.onBlur}
        onChange={value => input.onChange(value)}
        onFocus={input.onFocus}
      />
      {renderMessages && !messagesAboveLabel &&
        <Messages bottom error={error} warning={warning} />
      }
    </div>
  );
};

FormField.propTypes = propTypes;
FormField.defaultProps = defaultProps;

export default FormField;
