import './FormField.scss';
import React, { PropTypes } from 'react';
import classNames from 'classnames';

const propTypes = {
  autoComplete: PropTypes.bool,
  // Preferably use variants to style this component.
  className: PropTypes.string,
  // Contains data from redux-form, such as values
  input: PropTypes.object,
  // E.g. 'input' or 'textArea'
  element: PropTypes.string.isRequired,
  // Text above input field
  label: PropTypes.string,
  // Generated by Redux-form. Contains value and error data.
  // http://redux-form.com/6.4.3/docs/api/Field.md/
  meta: PropTypes.object,
  // Unique identifier. Used to link label to input.
  id: PropTypes.string.isRequired,
  placeholder: PropTypes.string,
  // Number of rows for textAreas
  rows: PropTypes.number,
  // HTML input type, e.g. 'email'
  type: PropTypes.string,
  // Modify te look and feel of the FormField
  variant: PropTypes.oneOf(['material', 'preview']),
};

const defaultProps = {
  autoComplete: false,
  meta: {},
  variant: 'default',
};

/**
 * Creates a field for forms. Use with redux-form Field if possible.
 * @returns {component} Component
 */
const FormField = ({
  autoComplete,
  className,
  rows,
  placeholder,
  input,
  element,
  label,
  type,
  id,
  variant,
  meta: {
    active,
    dirty,
    error,
    touched,
    warning,
  },
}) => {
  const Element = element;

  const classes = classNames({
    Field: true,
    [`Field--variant-${variant}`]: variant,
    'Field--active': active,
    'Field--dirty': dirty,
    'Field--textarea': (type === 'textarea'),
    className,
  });

  return (
    <div className={`Field ${className} ${classes}`}>
      {label &&
        <label
          className="Field__label"
          htmlFor={id}
        >
          {label}
        </label>
      }
      <Element
        {...input}
        autoComplete={autoComplete}
        className="Field__input"
        id={id}
        placeholder={placeholder}
        rows={rows}
        type={type}
      />
      {touched && (error || warning) &&
        <div className="Field__messages">
          {((error &&
            <span className="Field__error">
              {error}
            </span>
          ) || (warning &&
            <span className="Field__warning">
              {warning}
            </span>
          ))}
        </div>
      }
    </div>
  );
};

FormField.propTypes = propTypes;
FormField.defaultProps = defaultProps;

export default FormField;
