export const GET_PERSONS = 'GET_PERSONS';
export const GET_PERSON = 'GET_PERSON';
export const GET_MOTIONS = 'GET_MOTIONS';
export const GET_MOTION = 'GET_MOTION';

export const GET_ARGUMENT = 'GET_ARGUMENT';
export const GET_COUNT = 'GET_COUNT';
export const GET_VOTE = 'GET_VOTE';
export const GET_VOTE_EVENT = 'GET_VOTE_EVENT';

export const FETCH_DOCUMENT_REQUEST = 'FETCH_DOCUMENT_REQUEST';
export const FETCH_DOCUMENT_SUCCESS = 'FETCH_DOCUMENT_SUCCESS';
export const FETCH_DOCUMENT_FAILURE = 'FETCH_DOCUMENT_FAILURE';

export const TOGGLE_DRAWER = 'TOGGLE_DRAWER';
export const SET_HIT_COUNT = 'SET_HIT_COUNT';
