export const FETCH_MOTIONS_REQUEST = 'FETCH_MOTIONS_REQUEST';
export const FETCH_MOTIONS_SUCCESS = 'FETCH_MOTIONS_SUCCESS';
export const FETCH_MOTIONS_FAILURE = 'FETCH_MOTIONS_FAILURE';

export const UPDATE_VOTE_TALLY = 'UPDATE_VOTE_TALLY';

export const SET_HOVER_CARD = 'SET_HOVER_CARD';
export const REMOVE_HOVER_CARD = 'REMOVE_HOVER_CARD';
