export const FETCH_MOTIONS_REQUEST = 'FETCH_MOTIONS_REQUEST';
export const FETCH_MOTIONS_SUCCESS = 'FETCH_MOTIONS_SUCCESS';
export const FETCH_MOTIONS_FAILURE = 'FETCH_MOTIONS_FAILURE';

export const UPDATE_VOTE_TALLY = 'UPDATE_VOTE_TALLY';
