export const SWIPE_CONFIG = Object.freeze({
  cardScaleAmount: 0.06,
  confirmSlideDistanceLarge: 800,
  confirmSlideDistanceSmall: 400,
  confirmVoteThresholdLarge: 200,
  confirmVoteThresholdSmall: 100,
  deadzoneAmount: 30,
  iconOpacityModifier: 0.02,
  iconShadowBlurModifier: 8,
  iconShadowOpacityModifier: 40,
  iconShadowSpreadModifier: 9,
  overlayBackdropBlurModifier: 5,
  overlayColorNo: '#CC1F1F',
  overlayColorYes: '#46A644',
  overlayOpacityModifier: 0.005,
  rotateModifier: 0.035,
  shadowAlphaMax: 1.2,
  shadowAlphaMin: 0.6,
  shadowModifierMax: 1.3,
  shadowModifierMin: 0.3,
  springFriction: 9,
  springFrictionVoteAnimation: 30,
  springMass: 0.2,
  springTension: 200,
  verticalClamp: 50,
});
